#!/bin/bash

# for this to work you must configure sudo such that
# it will be able to run the command without password
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=display_added action="sleep 1 && $HOME/.config/yabai/create_spaces.sh"
yabai -m signal --add event=display_removed action="sleep 1 && $HOME/.config/yabai/create_spaces.sh"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"

$HOME/.config/yabai/create_spaces.sh

yabai -m config layout                         bsp           \
                debug_output                   on            \
                window_placement               second_child  \
                top_padding                    20            \
                bottom_padding                 10            \
                left_padding                   10            \
                right_padding                  10            \
                window_gap                     8             \
                auto_balance                   off           \
                split_ratio                    0.5           \
                mouse_modifier                 ctrl          \
                mouse_action2                  swap          \
                mouse_action1                  resize 

yabai -m config focus_follows_mouse           off           \
                mouse_follows_focus           off           \
                window_topmost                off           \
                window_shadow                 on            \
                window_opacity                on            \
                window_opacity_duration       0.15          \
                active_window_opacity         1.0           \
                normal_window_opacity         0.95          \
                window_border                 on            \
                window_border_width           6             \
                active_window_border_color    0xaaa6e3a1    \
                normal_window_border_color    0xaa94e2d5    \
                insert_feedback_color         0xaad75f57    \
                window_border_radius          11            \
                window_animation_duration     0.22          \
                external_bar                  all:30:0

# Diable Yabai form resizing apps.
yabai -m rule --add app="^System Preferences$" layer=above manage=off
yabai -m rule --add app="^Karabiner-Elements$" layer=above manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" layer=above manage=off
yabai -m rule --add app="^Keka$" layer=above manage=off
yabai -m rule --add app="^Activity Monitor$" layer=above manage=off
yabai -m rule --add app="^AppCleaner$" layer=above manage=off
yabai -m rule --add app="^Finder$" layer=above manage=off
yabai -m rule --add app="^Rocket$" layer=above manage=off
yabai -m rule --add app="^ConfigDialog$" layer=above manage=off
yabai -m rule --add app="^DictionaryTool$" layer=above manage=off
yabai -m rule --add app="^Audio MIDI Setup$" layer=above manage=off
yabai -m rule --add app="^ColorSync Utility$" layer=above manage=off
yabai -m rule --add app="^Console$" layer=above manage=off
yabai -m rule --add app="^Digital Color Meter$" layer=above manage=off
yabai -m rule --add app="^Archive Utility$" layer=above manage=off
yabai -m rule --add app="^Tidal$" layer=above manage=off
# yabai -m rule --add app="^Spotify$" layer=above manage=off
yabai -m rule --add app="^Stardew Valley$" layer=above manage=off
yabai -m rule --add app="^SuperTux$" layer=above manage=off
yabai -m rule --add app="^OpenEmu$" layer=above manage=off
yabai -m rule --add app="^Keychain Access$" layer=above manage=off
yabai -m rule --add app="^System Information$" layer=above manage=off
yabai -m rule --add app="^PenTablet$" layer=above manage=off
yabai -m rule --add app="^AdGuard for Safari$" layer=above manage=off
yabai -m rule --add app="^Calculator$" layer=above manage=off
yabai -m rule --add app="^Alfred Preferences$" layer=above manage=off
yabai -m rule --add app="^Stats$" layer=above manage=off
yabai -m rule --add app="^TIDAL$" layer=above manage=off
yabai -m rule --add app="^Latest$" layer=above manage=off

# Fix some applications from not being managed
# yabai -m rule --add app=Emacs manage=on space=2

# Auto update Yabai from HEAD via brew
# YABAI_CERT=yabai-cert sh -c "$(curl -fsSL "https://git.io/update-yabai")" &

echo "yabai configuration loaded.."
