# style name or JSON path (default "auto")
style: "/Users/skinofmyeden/.dotfiles/ricing/themes/catppuccin/glamour/macchiato.json"
# style: "dark"
# style: "dracula"
# show local files only; no network (TUI-mode only)
local: false
# mouse support (TUI-mode only)
mouse: true 
# use pager to display markdown
pager: true 
# word-wrap at width
width: 70
