lastupdatecheck: 0
recentrepos:
- /Users/skinofmyeden/.dotfiles
- /Users/skinofmyeden/Documents/start-page
- /Volumes/LIVISU/livs/zotero
- /Users/skinofmyeden/.config/nvim/lua/user
- /Volumes/LIVISU/livs/programming/git-professional/livisupajares.github.io
startuppopupversion: 5
customcommandshistory:
- :q
- q
hidecommandlog: false
ignorewhitespaceindiffview: false
